// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace taskManager.Models.CompiledModels
{
    public partial class DataContextModel
    {
        partial void Initialize()
        {
            var taskModel = TaskModelEntityType.Create(this);
            var taskType = TaskTypeEntityType.Create(this);
            var user = UserEntityType.Create(this);

            TaskModelEntityType.CreateForeignKey1(taskModel, taskType);
            TaskModelEntityType.CreateForeignKey2(taskModel, user);

            TaskModelEntityType.CreateAnnotations(taskModel);
            TaskTypeEntityType.CreateAnnotations(taskType);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "8.0.8");
        }
    }
}
